[package]
name = "image_asset_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
image = "0.25.5"
tokio = { version = "1.0", features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.0"