[package]
name = "image_conversion"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
webp = "0.3.0"
avif-serialize = "0.8.2"
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4"
dotenv = "0.15"
anyhow = "1.0"
